version: '3.5'
services:
    mongo:
        image: mongo:3.6.17-xenial
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes: 
            - /home/dev/projects/samisdat/zoo/mongo-data:/data/db 

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

    api:
        image: zoo:latest
        volumes: 
            - /home/dev/projects/samisdat/zoo/api:/app 
        ports:
            - 3000:3000
