version: '3.5'
services:
    mongo:
        image: mongo:3.6.17-xenial
        restart: always
        volumes:
            - /home/dev/projects/samisdat/zoo/mongo-data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081

    api:
        image: zoo:latest
        volumes:
            - /home/dev/projects/samisdat/zoo/api:/home/node/app
            - /home/dev/projects/samisdat/zoo/frontend:/home/node/frontend
        ports:
            - 3000:3000
            - 3001:3001
        links:
            - mongo:mongo
