GET http://localhost:3000/

###

GET http://localhost:3000/pokemons

###

GET http://localhost:3000/subscribers/5e655cc3f4c61c000d0068a4

###

POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "BPe",
  "gender": "male",
  "type": "foo",
  "height": 10,
  "weight": 20,
  "photo": "String"
}

###
DELETE http://localhost:3000/pokemon/5e65759231af1a0252120d75

###
PUT http://localhost:3000/pokemon/5e65759231af1a0252120d75
Content-Type: application/json 

{
  "name": "Tommy"
}

###
